markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Qui√©n te financia
featured-image: //images/post/
url: http://quientefinancia.cl
description: Que no nos gobierne el poder invisible
twitter: ciudadanoi
github: ciudadanointeligente
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
hashtag: '#QuienTeFinancia'
